version: '3.8'

services:
  hebrew-rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hebrew-rag-system
    ports:
      - "8000:8000"  # FastAPI backend
      - "11434:11434"  # Ollama
    volumes:
      # Persistent storage
      - ./storage:/app/storage
      # Model cache (optional - for faster restarts)
      - model_cache:/app/models
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - OLLAMA_HOST=http://localhost:11434
      - LLM_MODEL=gpt-oss:20b
      - EMBEDDING_MODEL=intfloat/multilingual-e5-large
      - DOTS_OCR_MODEL=rednote-hilab/dots.ocr
      - TESSERACT_LANG=heb+eng
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      - MAX_FILE_SIZE_MB=100
      - WATCH_DIRECTORY=/app/storage/watch
      - SCAN_INTERVAL_SECONDS=3600
      - ENABLE_PERIODIC_INDEXING=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - hebrew-rag-network

volumes:
  model_cache:
    driver: local

networks:
  hebrew-rag-network:
    driver: bridge 